import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import Card from '../components/Card'
import Footer from '../components/Footer'
import LinkComponent from '../components/LinkComponent'
import Navbar from '../components/Navbar'
import Search from '../components/Search'
import styles from '../styles/pages/Home.module.scss'

interface cardInfo {
	img: string,
	title: string,
	text: string
}

let cardInfos: cardInfo[] = [
	{
		img: '/images/icon-brand-recognition.svg',
		title: 'Brand Recognition',
		text: 'Boost your brand recognition with each click. Generic links don’t mean a thing. Branded links help instil confidence in your content.'
	},
	{
		img: '/images/icon-detailed-records.svg',
		title: 'Detailed Records',
		text: 'Gain insights into who is clicking your links. Knowing when and where people engage with your content helps inform better decisions.'
	},
	{
		img: '/images/icon-fully-customizable.svg',
		title: 'Fully Customizable',
		text: 'Improve brand awareness and content discoverability through customizable links, supercharging audience engagement.'
	},

]

interface LinkShape {
	originalLink: string,
	shortenedLink: string,
	justClicked: boolean
}

const Home: NextPage = () => {


	const [links, setLinks] = useState<LinkShape[]>([]);


	const changeCopyStatus = (index: number) => {
		setLinks(prev => {
			let newList: LinkShape[] = [];
			prev.forEach(l => {
				l.justClicked = false;
				newList.push(l);
			});

			newList[index].justClicked = true;
			return newList;
		})
	}

	const addNewLink = (short_url: string, original_url: string) => {
		let newLinks = links;
		const newLink: LinkShape = {
			originalLink: original_url,
			shortenedLink: short_url,
			justClicked: false
		}

		if (links.length >= 3) {
			newLinks.pop();
		}
		newLinks = [newLink, ...newLinks];
		setLinks(newLinks);
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Frontend Mentor | Shortly URL shortening API Challenge</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/images/favicon-32x32.png" />
			</Head>

			<header className={styles.header}>
				<nav className='container'>
					<Navbar />
				</nav>

				<div className={styles.hero + ' container'}>
					<div className={styles.hero_img}>
						<img src="/images/illustration-working.svg" alt="hero image" />
					</div>

					<div className={styles.hero_text}>
						<h1>More than just shorter links</h1>
						<p>Build your brand&apos;s recognition and get detailed insights
							on how your links are performing.</p>
						<Link href="/">
							<a>Get Started</a>
						</Link>
					</div>
				</div>

			</header>

			<main className={styles.main}>

				<section className={styles.section_1}>
					<div className={styles.search_component_container}>
						<div className={styles.search_component + ' container'}>
							<Search addNewLink={addNewLink} />
						</div>
					</div>

					<div className={styles.search_results + ' container'}>
						{
							links.map((link, index) => {
								return <LinkComponent
									key={index}
									index={index}
									originalLink={link.originalLink}
									shortenedLink={link.shortenedLink}
									justClicked={link.justClicked}
									changeCopyStatus={changeCopyStatus}
								/>
							})
						}
					</div>


					<div className='container'>
						<div className={styles.info}>
							<h1>Advanced Statistics</h1>
							<p>Track how your links are performing across the web with our
								advanced statistics dashboard.</p>
						</div>
					</div>

					<div className={styles.cards + ' container'}>
						<div className={styles.card_1}>
							<Card
								img_src={cardInfos[0].img}
								title={cardInfos[0].title}
								text={cardInfos[0].text}
							/>
						</div>

						<div className={styles.card_2}>
							<Card
								img_src={cardInfos[1].img}
								title={cardInfos[1].title}
								text={cardInfos[1].text}
							/>
						</div>

						<div className={styles.card_3}>
							<Card
								img_src={cardInfos[2].img}
								title={cardInfos[2].title}
								text={cardInfos[2].text}
							/>
						</div>
					</div>

					<div className={styles.get_started}>
						<h1>Boost your links today</h1>
						<Link href="/">
							<a>Get Started</a>
						</Link>
					</div>

				</section>

			</main>

			<footer className={styles.footer + ' container'}>
				<Footer />
				{/* <p>
					Challenge by <a href="https://www.frontendmentor.io?ref=challenge" rel="noreferrer" target="_blank">Frontend Mentor</a>.
					Coded by <a href="https://www.linkedin.com/in/segniadeba/">Segni Adeba</a>.
				</p> */}
			</footer>
		</div>
	)
}

export default Home
